- arduino/smartcar/smartcar.ino
The car moves forward until it detects an object and stops
> Obstacle avoidance

- android/.idea/.name
- android/app/src/main/AndroidManifest.xml
- android/app/src/main/java/com/example/android/LoginActivity.java
- android/app/src/main/java/com/example/android/MainActivity.java
- android/app/src/main/java/com/example/android/ManualActivity.java
- android/app/src/main/java/com/example/android/SignupActivity.java
- android/app/src/main/res/layout/activity_login.xml
- android/app/src/main/res/layout/activity_main.xml
- android/app/src/main/res/layout/activity_manual.xml
- android/app/src/main/res/layout/activity_signup.xml
I added the manual control windows and I think it looks good. Please take a look at it and let me know if I did a good job or not.
> App updates

- .github/workflows/arduino-build.yml
- android/.idea/.name
- android/.idea/jarRepositories.xml
- android/.idea/markdown-navigator-enh.xml
- android/.idea/markdown-navigator.xml
- android/app/build.gradle
- android/app/src/main/AndroidManifest.xml
- android/app/src/main/java/com/example/android/MainActivity.java
- android/app/src/main/java/com/example/android/ManualActivity.java
- android/app/src/main/java/com/example/android/MqttClient.java
- android/app/src/main/res/layout/activity_manual.xml
- android/build.gradle
- arduino/smartcar/smartcar.ino
An MQTT connection to the broker has been implemented in both the android side and the arduino file to make it possible to connect the car to app in order to be able to cotrol the car from the app through MQTT connection
closes #31
> Mqtt connectivity 

- android/app/src/main/java/com/example/android/User.java
Create User class to be able to create users and store their information
> Implement User

- android/app/src/main/java/com/example/android/Mailman.java
- android/app/src/main/java/com/example/android/Message.java
- android/app/src/main/java/com/example/android/Receiver.java
- android/app/src/main/java/com/example/android/User.java
Implement message class and created list of messages in the User class that is inherited by receiver and Mailman. The list will hold messages sent from and to the mailman and the receivers and the other way arround.
> Notifications

- android/.idea/compiler.xml
- android/.idea/misc.xml
- android/app/src/main/java/com/example/android/Controller.java
- android/app/src/main/java/com/example/android/Message.java
- android/app/src/main/java/com/example/android/User.java
The method implemented are to create receivers and mailmen, create a message, send a pick up notification and pickup confirmation message.
> Implement methods to handle notifications in the controller

- android/app/src/main/java/com/example/android/Controller.java
- android/app/src/main/java/com/example/android/Mailman.java
- android/app/src/main/java/com/example/android/Message.java
- android/app/src/main/java/com/example/android/Receiver.java
- android/app/src/main/java/com/example/android/User.java
User ID, Message ID are automatically generated now
> fix IDs generated automatically

- android/.idea/misc.xml
This contains the updated version of the master with corrections, the master has been merged locally then pushed again
> implement methods to create delivery, messages and display data

- android/.idea/misc.xml
Implemented a method to display the list of messages fo both, the mailman and the receiver
> Display the list of messages

- android/app/src/main/AndroidManifest.xml
- android/app/src/main/java/com/example/android/HomeActivity.java
- android/app/src/main/java/com/example/android/PickupNotificationActivity.java
- android/app/src/main/java/com/example/android/ReceiverActivity.java
- android/app/src/main/java/com/example/android/User.java
- android/app/src/main/res/layout/activity_home.xml
- android/app/src/main/res/layout/activity_manual.xml
- android/app/src/main/res/layout/activity_pickup_notification.xml
> Receiver and Send notification screens done.

- android/app/src/main/res/layout/activity_home.xml
Co-authored-by: MaabMohammedali <gusmaamo@student.gu.se>
> Fix button mention on the xml file

- android/app/src/main/AndroidManifest.xml
- android/app/src/main/java/com/example/android/Controller.java
- android/app/src/main/java/com/example/android/HomeActivity.java
- android/app/src/main/java/com/example/android/LoginActivity.java
- android/app/src/main/java/com/example/android/MainActivity.java
Created a mailman in the list and tested the password verification, when the password is wrong a toast pops up to ask to type credentials again
> Add a mailman and verify credentials to login

- android/app/src/main/AndroidManifest.xml
- android/app/src/main/java/com/example/android/Controller.java
- android/app/src/main/java/com/example/android/HomeActivity.java
- android/app/src/main/java/com/example/android/Mailman.java
- android/app/src/main/java/com/example/android/MailmanMessageListActivity.java
- android/app/src/main/java/com/example/android/MailmanMessageListAdapter.java
- android/app/src/main/java/com/example/android/MainActivity.java
- android/app/src/main/java/com/example/android/NotifyReceiverAdapter.java
- android/app/src/main/res/layout/activity_home.xml
- android/app/src/main/res/layout/activity_mailman_message_list.xml
- android/app/src/main/res/layout/adapter_mailman_message_list_view_layout.xml
Display list of messages for the mailman who is logged in.
> Implement Display the list of messages the logged in mailman received

- android/app/src/main/AndroidManifest.xml
- android/app/src/main/java/com/example/android/Controller.java
- android/app/src/main/java/com/example/android/HomeActivity.java
- android/app/src/main/java/com/example/android/LoginActivity.java
- android/app/src/main/java/com/example/android/MailmanHomeActivity.java
- android/app/src/main/java/com/example/android/ManualActivity.java
- android/app/src/main/java/com/example/android/Receiver.java
- android/app/src/main/java/com/example/android/ReceiverActivity.java
- android/app/src/main/java/com/example/android/ReceiverHomeActivity.java
- android/app/src/main/java/com/example/android/ReceiverMessageListActivity.java
- android/app/src/main/java/com/example/android/ReceiverMessageListAdapter.java
- android/app/src/main/res/layout/activity_receiver.xml
- android/app/src/main/res/layout/activity_receiver_message_list.xml
- android/app/src/main/res/layout/adapter_receiver_message_list_view_layout.xml
In this PR, we commited a bunch of fixes and features that are a UI to display the list of messages for a the logged in receiver, implemented log out for both the mailman and the receiver and implemented the login for the receiver
> Receiver message list and log out

- android/app/src/main/java/com/example/android/Controller.java
- android/app/src/main/java/com/example/android/LoginActivity.java
- android/app/src/main/java/com/example/android/Mailman.java
- android/app/src/main/java/com/example/android/MailmanMessageListAdapter.java
- android/app/src/main/java/com/example/android/MainActivity.java
- android/app/src/main/java/com/example/android/Message.java
- android/app/src/main/java/com/example/android/NotifyReceiverAdapter.java
- android/app/src/main/java/com/example/android/ReceiverMessageListAdapter.java
- android/app/src/main/res/layout/adapter_mailman_message_list_view_layout.xml
- android/app/src/main/res/layout/adapter_receiver_message_list_view_layout.xml
In this PR, the list of messages appear in the mailman version and the confirmation button is fuctional for the receiver, The list of meaages display the name of the sender and the message title. The confirmation button appear only when the message is "confirm pick-up" to the user and disabled once the receiver clicks on it and sends a confirmation message  to the mailman
> Receiver message list confirmation button

- android/app/src/main/java/com/example/android/Controller.java
- android/app/src/main/java/com/example/android/LoginActivity.java
- android/app/src/main/java/com/example/android/Mailman.java
- android/app/src/main/java/com/example/android/MailmanMessageListAdapter.java
- android/app/src/main/java/com/example/android/Message.java
- android/app/src/main/java/com/example/android/NotifyReceiverAdapter.java
- android/app/src/main/java/com/example/android/Receiver.java
- android/app/src/main/java/com/example/android/ReceiverMessageListAdapter.java
- android/app/src/main/res/layout/adapter_mailman_message_list_view_layout.xml
- android/app/src/main/res/layout/adapter_notify_receiver_list_view_layout.xml
- android/app/src/main/res/layout/adapter_receiver_list_view_layout.xml
- android/app/src/main/res/layout/adapter_receiver_message_list_view_layout.xml
Changes
1. Add  two buttons in the receivers list of message to inform his/her availability to expect a delivery
2. Change button colors for more visual
3. disable the buttons once clicked on
Issues
#116 #115
> #116  #115 Implement buttons to inform the mailman if the receiver is available to expect a delivery

- README.md
> Update app logo README.md

- android/app/src/main/java/com/example/android/Controller.java
- android/app/src/main/java/com/example/android/MailmanMessageListAdapter.java
Problem
Wrong implemetation to find the mailman
Changes
Create a method to get the logged in mailman that wante to send the pick up message and returns the mailman ID
Implement the call to a method that seaarches the mailman by ID in the list to get the position in sendPickUp() method
get the name and ID of the sender
> #132 #133 Fix mailman search to send pick up notification

- android/app/src/main/java/com/example/android/Controller.java
- android/app/src/main/java/com/example/android/NotifyReceiverAdapter.java
Changes
sendExpectDelivery() uses call to fetch the logged in mailman by ID 
solves issue #137 #135
> #135 #137 Fix mailman search

- android/app/src/main/java/com/example/android/Controller.java
- android/app/src/main/java/com/example/android/MailmanMessageListActivity.java
- android/app/src/main/java/com/example/android/Message.java
- android/app/src/main/java/com/example/android/MessageDialog.java
- android/app/src/main/java/com/example/android/ReceiverMessageListActivity.java
- android/app/src/main/java/com/example/android/ReceiverMessageListAdapter.java
- android/app/src/main/res/layout/adapter_receiver_message_list_view_layout.xml
When the users clicks on the received message, a popup dialog message appears with the sender's name and the content of the messagee
> Implement Message dialog popup

- android/app/build.gradle
- android/app/src/androidTest/java/smart/delirover/app/ExampleInstrumentedTest.java
- android/app/src/main/AndroidManifest.xml
- android/app/src/main/java/smart/delirover/app/Controller.java
- android/app/src/main/java/smart/delirover/app/LoginActivity.java
- android/app/src/main/java/smart/delirover/app/Mailman.java
- android/app/src/main/java/smart/delirover/app/MailmanHomeActivity.java
- android/app/src/main/java/smart/delirover/app/MailmanMessageListActivity.java
- android/app/src/main/java/smart/delirover/app/MailmanMessageListAdapter.java
- android/app/src/main/java/smart/delirover/app/MainActivity.java
- android/app/src/main/java/smart/delirover/app/ManualActivity.java
- android/app/src/main/java/smart/delirover/app/Message.java
- android/app/src/main/java/smart/delirover/app/MessageDialog.java
- android/app/src/main/java/smart/delirover/app/MqttClient.java
- android/app/src/main/java/smart/delirover/app/NotifyReceiverActivity.java
- android/app/src/main/java/smart/delirover/app/NotifyReceiverAdapter.java
- android/app/src/main/java/smart/delirover/app/Receiver.java
- android/app/src/main/java/smart/delirover/app/ReceiverHomeActivity.java
- android/app/src/main/java/smart/delirover/app/ReceiverListActivity.java
- android/app/src/main/java/smart/delirover/app/ReceiverListAdapter.java
- android/app/src/main/java/smart/delirover/app/ReceiverMessageListActivity.java
- android/app/src/main/java/smart/delirover/app/ReceiverMessageListAdapter.java
- android/app/src/main/java/smart/delirover/app/User.java
- android/app/src/main/res/layout/activity_mailman_message_list.xml
- android/app/src/main/res/layout/activity_notify_receiver.xml
- android/app/src/main/res/layout/activity_receiver_list.xml
- android/app/src/main/res/layout/activity_receiver_message_list.xml
- android/app/src/test/java/smart/delirover/app/ExampleUnitTest.java
> #113 #170 add message time, fix typo in not availabe message, changepackage name

- android/app/src/main/AndroidManifest.xml
- android/app/src/main/java/smart/delirover/app/MailmanHomeActivity.java
- android/app/src/main/java/smart/delirover/app/MailmanTraveledDistanceActivity.java
- android/app/src/main/java/smart/delirover/app/ManualActivity.java
- android/app/src/main/res/layout/activity_home.xml
- android/app/src/main/res/layout/activity_mailman_traveled_distance.xml
- arduino/smartcar/smartcar.ino
I Rewrote  "MailmanTraveledDistanceActivity.java", reusing the existing java class in "mqttclient.java".
And I simplified the  layout of "MailmanTraveledDistanceActivity" , deleting unnecessary  widgets. Only kept two TextViews to show real-time odometer data.
New_Function_ScreenShots(3PCS):
> Adding function: display real-time odometer data.
